### ISSUE TITLE
Request to add pot-desktop 

### ISSUE THREAD

**Issue by aka-phrankie** [hoilc/scoop-lemon#1246]
### Name

pot-desktop

### Description

POT:Cross -platform words translation and OCR
Your last translation software               

### Homepage

https://github.com/pot-app/pot-desktop

### Download Link(s)

https://github.com/pot-app/pot-desktop/releases

### Some Indication of Popularity/Repute

A cross-platform software for text translation and recognition.  9.4K star.

**Comment by hoilc** [comment]
Try `scoop install lemon/pot` :)

https://github.com/hoilc/scoop-lemon/blob/master/bucket/pot.json
