### ISSUE TITLE
autok3s@0.9.3: hash check failed

### ISSUE THREAD

**Issue by longredzhong** [hoilc/scoop-lemon#1352]
Installing 'autok3s' (0.9.3) [64bit] from 'hoilc_scoop-lemon' bucket
autok3s_windows_amd64.exe (28.3 MB) [========================================================================================================================] 100%
Checking hash of autok3s_windows_amd64.exe ... ERROR Hash check failed!
App:         hoilc_scoop-lemon/autok3s
URL:         https://github.com/cnrancher/autok3s/releases/download/v0.9.3/autok3s_windows_amd64.exe#/autok3s.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    850cd26c83c8b98a7a32b032abf23d8da8bc84ab34ef4149192480add29ca6c8
Actual:      9486134f871a4998371df206747463de67f296ab05f40f817605ac0d00dc7fc5

**Comment by hoilc** [comment]
You are right. Thank you for reporting.
