### ISSUE TITLE
dataflare@20241123: hash check failed

### ISSUE THREAD

**Issue by Jadeiin** [hoilc/scoop-lemon#1378]
ERROR Hash check failed!
App:         lemon/dataflare
URL:         https://assets.dataflare.app/release/windows/x86_64/Dataflare-Setup.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    5d00768e89959383a9e1f36a1ff9a4ae592930522cdba17eb817c7b5edced314
Actual:      a8fae065a72037ffd95f62674aa8a3a459d410941976c050e05c19c4c09d4167

**Comment by hoilc** [comment]
You are right. Thank you for reporting.

**Comment by hoilc** [comment]
e3ef76b
