### ISSUE TITLE
 piclist    ERROR Hash check failed!

### ISSUE THREAD

**Issue by cnxv** [hoilc/scoop-lemon#1387]
PicList-Setup-2.9.6-x64.exe (97.8 MB) [=======================================================] 100%
Checking hash of PicList-Setup-2.9.6-x64.exe ... ERROR Hash check failed!
App:         lemon/piclist
URL:         https://github.com/Kuingsmile/PicList/releases/download/v2.9.6/PicList-Setup-2.9.6-x64.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    385cc9d88654d48be62ac807da5984370365f4694b3f1006c456e985779a9f82a79662adc761a635f22ea25c2a650aeee7b0dabbbf796059438e3ba10f32d631
Actual:      be9ae89a72b596055feaac64e5f6939f60fdc618cf77448d7426c3e65cc026f94e7e8ff5b98faac78a4b9b22a5ab7c2fdfa09255b6a224d9fef24f5bb9c00cf3

**Comment by hoilc** [comment]
Thank you for reporting.
