### ISSUE TITLE
Dnscontrol: auto update failed

### ISSUE THREAD

**Issue by riku22** [hoilc/scoop-lemon#777]
Hello.

[V4.2.0 of dnscontrol has been released](https://github.com/StackExchange/dnscontrol/releases/tag/v4.2.0).
Due to the end of distribution of 32-bit binaries from this version, it seems that the automatic update check failed and `dnscontrol.json` was not updated.
I think that deleting `32bit` from `architecture` of `autoupdate` in the corresponding JSON will solve it, but could you check it?

**Comment by hoilc** [comment]
You are right. Thanks for reporting.
