### ISSUE TITLE
😶‍🌫️ zotero-beta installation file optimization: add deeplink support

### ISSUE THREAD

**Issue by aka-phrankie** [hoilc/scoop-lemon#936]
I noticed that your software has not yet registered Zotero as the default handler for the zotero:// protocol. Therefore, I sincerely suggest you consider adding the code to register the zotero:// protocol in the software installation process or settings interface.The benefits of doing so are: It allows users to open zotero:// links directly in Zotero without manually selecting the program.

This is the official repository Zotero 6, which has implemented the registration of Zotero as the default handler for the 'zotero://' URL protocol.
- https://github.com/ScoopInstaller/Extras/blob/master/bucket/zotero.json  

![chrome_231116_2240_10](https://github.com/hoilc/scoop-lemon/assets/44957887/0ccf0531-96f0-4703-b988-7dc76795a6ee)

This is the json address of the zotero-beta application in this warehouse. It seems that it can be combined with ps1 file completion. I hope it can reduce your workload. 
- https://github.com/hoilc/scoop-lemon/blob/master/bucket/zotero-beta.json

This is the URL linking to the command-line interface documentation for Zotero version 6, as referenced in the repository. 
- https:github.com/ScoopInstaller/Extras/blob/master/scripts/zotero/install-zotero-url-protocol.ps1

**Comment by hoilc** [comment]
Thank you.
